### ISSUE TITLE
Logoen ser pikselert ut langt ute og grei ut zoomet inn

### ISSUE THREAD

**Issue by Goplen** [fui/fui.github.io#22]

**Comment by karlhto** [comment]
Det omvendte er tilfellet med burger-menyen, men den er vel ikke vektor?

**Comment by karlhto** [comment]
Usikker på om vi kan gjøre så mye med dette, og det har heller ikke så mye å si. Er viktigere med burgermenyen: vi burde finne en høyere oppløsning av den elns.
